# fly.toml app configuration file
app = "lasop-server-vault"
primary_region = "jnb"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  # HTTP readiness check
  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/ready"



 
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
