# fly.toml
app = "lasop-suit-server"
primary_region = "lhr"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

  SMTP_HOST = "server60.web-hosting.com"
  SMTP_PORT = "587"
  SMTP_SECURE = "false"
  FROM_EMAIL = "no-reply@lasop.net"
  FROM_NAME = "LASOP"
  REPLY_TO_EMAIL = "no-reply@lasop.net"
  SMTP_TLS_SERVERNAME = "server60.web-hosting.com"
  SMTP_REJECT_UNAUTHORIZED = "true"
  EMAIL_DRY_RUN = "0"
  MAILER_DEBUG = "0"

  IMAP_HOST = "server60.web-hosting.com"
  IMAP_PORT = "993"
  IMAP_SECURE = "true"
  IMAP_TLS_SERVERNAME = "server60.web-hosting.com"
  IMAP_USER = "no-reply@lasop.net"
  IMAP_MAILBOX = "INBOX"
  IMAP_LOOKBACK_MINUTES = "1440"
  IMAP_FALLBACK_WINDOW = "300"
  IMAP_FETCH_CHUNK = "50"
  IMAP_LOG = "0"

  OTP_EXP_MINUTES = "10"
  EXPOSE_OTP_IN_DEV = "0"
  ALLOW_OTP_FALLBACK = "0"

  CLIENT_ORIGIN = "https://your-frontend-domain.com"
  API_PUBLIC_BASE_URL = "https://lasop-suit-server.fly.dev"

  REQUIRE_AUTH = "1"

  ORG_PHONE = "+2347025713326"
  ORG_WEBSITE = "https://www.lasop.net"

  META_PIXEL_ID = "825116977010378"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/ready"

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/"

  [services.http_options]
    force_https = true

[vm]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[machines]
  auto_start = true
  auto_stop = false
  min_machines_running = 1
