# fly.toml app configuration file
app = "lasop-server-vault"
primary_region = "jnb"

[build]

[env]
  PORT = "3000" # keep app/server/Dockerfile aligned to 3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  processes = ["app"]
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
