# fly.toml app configuration file
app = "lasop-server-vault"
primary_region = "jnb"

[build]

[env]
  PORT = "3000"

# Service configuration
[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Health checks
  [[services.http_checks]] # Readiness check
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/ready"

  [[services.http_checks]] # Liveness check
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/"

  [services.http_options]
    force_https = true

[vm]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[machines]
  auto_start = true
  auto_stop = false
  min_machines_running = 1
